[root@p054lnxfore01 05-foreman-ssl.d]# pwd
/!backuphttpd/httpd/conf.d/05-foreman-ssl.d
[root@p054lnxfore01 05-foreman-ssl.d]# cat
foreman-oidc2.conf  katello.conf
[root@p054lnxfore01 05-foreman-ssl.d]# cat foreman-oidc2.conf
    # Microsoft Entra ID (Azure AD) OIDC Configuration
    OIDCProviderMetadataURL https://login.microsoftonline.com/2a9f86a9-29e7-44bd-8863-849373d53db8/v2.0/.well-known/openid-configuration
    OIDCClientID aa676036-3095-441f-8b19-dac4703030cc
    OIDCClientSecret NZg8Q~JNXUUmsQNLaoXW12Yfgeyjk1aZY.CQoa2S
    OIDCRedirectURI https://foreman.epiqcorp.com/users/extlogin/redirect_uri
    OIDCCryptoPassphrase some_random_string
    OIDCScope "openid email profile"
    OIDCResponseType id_token
        OIDCRemoteUserClaim preferred_username

<Location /users/extlogin>
    AuthType openid-connect
    Require valid-user
    LogLevel debug

    RequestHeader set REMOTE_USER %{OIDC_CLAIM_preferred_username}e
    RequestHeader set REMOTE_USER_EMAIL %{OIDC_CLAIM_email}e
    RequestHeader set REMOTE_USER_FIRSTNAME %{OIDC_CLAIM_given_name}e
    RequestHeader set REMOTE_USER_LASTNAME %{OIDC_CLAIM_family_name}e
</Location>

