[NOTICE]   (58565) : haproxy version is 2.8.14-c23fe91
[NOTICE]   (58565) : path to executable is /usr/sbin/haproxy
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'rdfarm19' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'rdfarm19-mfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'rdfarm19365' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'rdfarm19365mfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarmSXA' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarmSXAmfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm22SXA' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm22SXAmfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm365' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm365mfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm01' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : parsing [haproxy.cfg:52] : 'option httplog' not usable with proxy 'RDFarm01mfa' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'rdfarm19' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'rdfarm19-mfa' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'rdfarm19365' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'rdfarm19365mfa' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarmSXA' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarmSXAmfa' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm22SXA' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm22SXAmfa' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm365' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm365mfa' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm01' as it requires HTTP mode.
[WARNING]  (58565) : config : 'option forwardfor' ignored for proxy 'RDFarm01mfa' as it requires HTTP mode.
[NOTICE]   (58565) : config : config: Can't open global server state file '/etc/haproxy/haproxy.state': No such file or directory
Warnings were found.
Configuration file is valid
