
#!/usr/bin/env bash
# rsyslog_suppress_nfs.sh
#
# Suppress (or route) noisy NFS kernel messages:
#   - "nfs: server <host> not responding, still trying"
#   - "nfs: server <host> OK"                  (optional)
#   - "rpc_check_timeout: ... callbacks suppressed"
#   - "call_decode: ... callbacks suppressed"  (optional)
#
# Works for kernel lines arriving via imjournal (systemd) or imklog.
#
# USAGE:
#   sudo ./rsyslog_suppress_nfs.sh --apply
#   sudo ./rsyslog_suppress_nfs.sh --apply --include-call-decode
#   sudo ./rsyslog_suppress_nfs.sh --apply --also-silence-ok
#   sudo ./rsyslog_suppress_nfs.sh --apply --route-to-file /var/log/nfs-noise.log
#   sudo ./rsyslog_suppress_nfs.sh --revert
#
# OPTIONS:
#   --apply                 Create/update filters
#   --revert                Remove created filters
#   --include-call-decode   Also match "call_decode" lines
#   --also-silence-ok       Also suppress "nfs: server ... OK" lines
#   --route-to-file PATH    Route matches to PATH (instead of dropping) and stop
#   --dry-run               Show what would change without applying
#
# EXIT CODES: 0 success; nonzero on error.

set -euo pipefail

RSYSLOG_DIR="/etc/rsyslog.d"
CONF="${RSYSLOG_DIR}/01-nfs-noise-quiet.conf"   # ensure it loads before 50-default.conf

DO_APPLY=0
DO_REVERT=0
DRY=0
INCLUDE_CALL_DECODE=0
ALSO_SILENCE_OK=0
ROUTE_TO_FILE=""

msg(){ echo "[*] $*"; }
err(){ echo "[!] $*" >&2; }
die(){ err "$@"; exit 1; }
have(){ command -v "$1" >/dev/null 2>&1; }

while (( "$#" )); do
  case "$1" in
    --apply) DO_APPLY=1 ;;
    --revert) DO_REVERT=1 ;;
    --dry-run) DRY=1 ;;
    --include-call-decode) INCLUDE_CALL_DECODE=1 ;;
    --also-silence-ok) ALSO_SILENCE_OK=1 ;;
    --route-to-file) shift; ROUTE_TO_FILE="${1:-}"; [[ -n "$ROUTE_TO_FILE" ]] || die "--route-to-file requires a path";;
    -h|--help)
      sed -n '1,120p' "$0" | sed -n '2,90p' | sed 's/^# \{0,1\}//'
      cat <<EOF

Examples:
  sudo $0 --apply
  sudo $0 --apply --include-call-decode
  sudo $0 --apply --also-silence-ok --route-to-file /var/log/nfs-noise.log
  sudo $0 --revert
EOF
      exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
  shift
done

(( EUID == 0 )) || die "Run as root (sudo)."
[[ -d "$RSYSLOG_DIR" ]] || die "$RSYSLOG_DIR not found (is rsyslog installed?)."
(( DO_APPLY || DO_REVERT )) || die "Specify --apply or --revert (see --help)."

validate_rsyslog(){ have rsyslogd && rsyslogd -N1 >/dev/null; }
restart_rsyslog(){ if have systemctl; then systemctl restart rsyslog; else service rsyslog restart; fi; }

backup_if_exists(){
  local f="$1"; [[ -f "$f" ]] || return 0
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local bak="${f}.bak.${ts}"
  if (( DRY )); then msg "Would back up: $f -> $bak"; else cp -a "$f" "$bak"; msg "Backed up: $f -> $bak"; fi
}

write_file(){
  local p="$1" c="$2"
  if (( DRY )); then msg "Would write $p with:\n----8<----\n$c\n---->8----"; else
    backup_if_exists "$p"; printf "%s\n" "$c" > "$p"; msg "Wrote: $p"
  fi
}

remove_file(){
  local p="$1"
  if [[ -f "$p" ]]; then
    if (( DRY )); then msg "Would remove $p"; else rm -f "$p"; msg "Removed: $p"; fi
  else
    msg "No file to remove: $p"
  fi
}

if (( DO_REVERT )); then
  msg "Reverting NFS rsyslog filters…"
  remove_file "$CONF"
  if (( ! DRY )); then validate_rsyslog; restart_rsyslog; msg "rsyslog restarted."; else msg "Dry-run: no changes applied."; fi
  exit 0
fi

# ---------- Build the rule ----------
# Match kernel-originated lines robustly:
#  - facility == kern
#  - OR programname == "kernel"
#  - OR syslogtag begins with "kernel:"  (use regex; older rsyslog may not support startswith)
KERNEL_MATCH='(
  $syslogfacility-text == "kern"
  or $programname == "kernel"
  or re_match($syslogtag, "^kernel:")
)'

# Message conditions
COND='( re_match($msg, "nfs: server .* not responding, still trying") or $msg contains "rpc_check_timeout"'
(( INCLUDE_CALL_DECODE )) && COND+=' or $msg contains "call_decode"'
(( ALSO_SILENCE_OK )) && COND+=' or re_match($msg, "nfs: server .* OK")'
COND+=')'

# Action: drop or route
if [[ -n "$ROUTE_TO_FILE" ]]; then
  # ensure target directory exists
  if (( ! DRY )); then install -d -m 0755 "$(dirname "$ROUTE_TO_FILE")"; fi
  ACTION="{ action(type=\"omfile\" file=\"${ROUTE_TO_FILE}\"); stop }"
  HEADER="# ROUTE noisy NFS kernel messages to ${ROUTE_TO_FILE} and stop"
else
  ACTION="{ stop }"
  HEADER="# DROP noisy NFS kernel messages early (before kern.log/syslog)"
fi

CONTENT="# ${CONF##*/} — generated by rsyslog_suppress_nfs.sh
${HEADER}
# Works regardless of imjournal/imklog path.

if ( ${KERNEL_MATCH} and ${COND} ) then ${ACTION}
"

msg "Creating/updating rsyslog filter at high priority: $CONF"
write_file "$CONF" "$CONTENT"

if (( ! DRY )); then
  msg "Validating rsyslog configuration…"
  validate_rsyslog
  msg "Restarting rsyslog…"
  restart_rsyslog
  msg "Done."
  [[ -n "$ROUTE_TO_FILE" ]] && msg "Routing enabled → ${ROUTE_TO_FILE}" || msg "Noisy NFS lines will be dropped."
else
  msg "Dry-run: no changes applied."
fi
